version: '2'
services: 
    aplicacion: 
        container_name: aplicacion-php
        build:
            context: . 
            dockerfile: Dockerfile-local
        ports:
            - "80:80"
        environment:
            DB_USUARIO: root
            DB_PASSWORD: 1234
            DB_IP: 10.0.0.15
            DB_NOMBRE: brumDB
        volumes: 
            - ./:/var/www/html
    db:
        container_name: ContainerDB
        image: mysql:5.7 
        ports:
            - 3306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: brumDB
        volumes:
            - ./mysql:/var/lib/mysql
