---
- name: Configuración Gral
  become: true
  hosts: all
  tasks:
    
    - name: Setear Hostname
      hostname: name={{ inventory_hostname }}

    - name: Instalar repositorio epel
      yum:
        name:
          - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

    - name: Instalar paquetes comunes
      yum:
        name:
          - git
          - vim
          - mlocate
          - wget
          - pbzip2
          
    - name: Configurar zona horaria
      timezone:
        name: America/Montevideo
        
    - name: Docker Install
      yum:
        name:
          - docker
          - docker-compose
          
    - name: Docker Start
      systemd:
        state: started
        name: docker
        enabled: yes
        
    - name: Desactivar modulo SELinux del arranque 
      selinux:
        state: disabled
        
    - name: Desactivar modulo SELinux en el momento
      selinux:
        policy: targeted
        state: permissive
        
    - name: Apagar Firewalld
      systemd: 
        state: stopped
        name: firewalld
        enabled: False
       
       
    - name: Tareas Generales 
      include_tasks: /Proyecto-GSMF/Ansible/Tasks/ssh.yml
    
    - name: Tareas para ServerApp
      include_tasks: /Proyecto-GSMF/Ansible/Tasks/TasksServerApp.yml
      include_tasks: /Proyecto-GSMF/Ansible/Tasks/UsersAppAdmin.yml
  
    - name: Tareas para ServerDB:
      include_tasks: /Proyecto-GSMF/Ansible/Tasks/TasksServerDB.yml
      include_tasks: /Proyecto-GSMF/Ansible/Tasks/UsersDbAdmin.yml


 
