---
- name: Config Firewall
  become: true
  hosts: all
  tasks:
    
    - name: Desactivar modulo SELinux del arranque 
      selinux:
        state: disabled
        
    - name: Desactivar modulo SELinux en el momento
      selinux:
        policy: targeted
        state: permissive
        
    - name: Apagar Firewalld
      systemd: 
        state: stopped
        name: firewalld
        enabled: False
