---
    - name: Instalar paquetes comunes
      yum:
        name:
          - docker
          - docker-compose

    - name: Iniciar Docker
      systemd:
        state: started
        name: docker
        enabled: yes
        daemon_reload: true
