---

    - name: Crear dbAdmin
      user: 
        name: dbadmin
        comment: DB Admin user
        group: wheel
        password: "MIIJKAIBAAKCAgEAxjEkhWbQiiKaz4f0PEY+guE+ktHB1izR64yssuqZw40z/PwE
                  9vn75FDomRKmJjV7oPgyoPyQbFxTrPnG4c+/wdzDAqBESjgBtcDX072sBmwHV/Aj
                  Mp0ttDvN8u9yIUdTvFY0lBqCb4ZDevbWiD+rEA2xKascNFVQtdRQOjvasbGdfZrm
                  B0egtVgh1lxM+haRrV+1zF1ZW9QR/ekkNsjbc/l0FBp8IZC5k5Wxoe5MerzwvkYv
                  w5f2WrqNi1LjNG1QNTFABgpI/priEjVPfSkvh1gbsmIG+NRchJWXK73FFAZpXGwG
                  gnwNW98luOZXj5M0+AaiB64RTY5/rGBq0yuxO9f2cw1f9RgnWRkdhd6hTIbMwBww
                  pcZnpflJrdFV30CKNcuLvSIaQinNZ1bSFhRUJtJaz4lK8PPBByYdnrkaW4qb5LNf
                  +YVotkQ7Hw+JCCx3U4e09Au8hXCUb6lhpl7gHNlxzoW8XutsLLba9RB2MM1rfQ0C
                  O0FELQs3Cr2d7o0/+ecNpxQuKgXENT65VjrPoce0cyZ9q/rSsjq4aoFIDMntj/oW
                  YWxFE20xPhhaKUZ9v3D9uoi/7Ke6RzgEgY0UyaNI7f9SYQP4x/SE2NiFJi/aNGyJ
                  WFpkHoW0MMfmLiJQkgvyEVag9k7jwWbmUkWMmicYgaBr0ewVxQ6sPMSmK2kCAwEA
                  AQKCAgAhf4rhtVgIEQNDkoIYcfL84h9WZ3ewwJCWlIdYEkj9AW/JEbuxFt2ZYId/
                  3+QPTzjfIzRDe4zZk91cvjb8UcXieXLIjdgdB0xasQaJtmRODZJMLb11P5XLAdS0
                  e/45W7nuek+WvMhRG0tqjDAEhWZfZ0ELfu1cdxMWOJV60kULha7N3RGGJ3glTokh
                  lyY3mvryZ9vtd9WzrKuB1BcX32kgOAiDoVpbvf9vz3xfl0x77lVug6RtFdFA0ok8
                  BD18zgEhjHp6yuA9kGYnl7UgvYZYBO9hfioZgqNEkZgkf4XA9bh3M5cCFP+ZCKVy
                  lBQ2ozXvugdG7wfjqPMxanaDzL2+yEyCS9l0uWQaI/YW8SImL93NC5GdNR/pVmcS
                  z5OVB91vGXobBsDluedS0vRdPqxUwnsLY+tMlofzFi134nOx63W9btewDoFf8pcZ
                  OiBrm4mOQPMRtF8rR2ZdKz3kxZa3mMwBECJkMgns/6MYQzfkJMENo6SMkDCfLl9m
                  ggBtSqU+1/UE63lK96jvq4QTOoasJhiRaHx5pjfZqHackP+dNjXERqBCY7lsnmuo
                  noD5uwRdFm+raqRypF8HRRrmJeSzyTsWPG1nEpD38rLH4LJP7gSgY7swHZ2F3DYH
                  W4y7xDeMR6vR14cEheqTVqqWz+QECwXKW4bZHhUimOrSkFmYJQKCAQEA8uUlW1ZL
                  MXZ9f6bm45lzKUa0Qnc1gwkVivxuYgr1n1NopxU/c3T3OiWMiUy8LoPsoPNW7VrY
                  RnNCjUy53izZA2jhMnDTWvE+eq31qN1k5ShHmqib257LVGrzlXmZVyBEoFdVv2HL
                  NPwF4WWZavLWoJRUtYGPDWlSOhh1yGMDnc5G5XdNSTAh1TIyafxg6Q6YA80DNrt3
                  48y9t8mOcmBYg41HSp32C9J79zmU6oO8HZmCccm9f0n1BoqD04ci/JbAIItndXta
                  NAyPg6/Qm+2WUjbfsXmnrFVdGYUjpymfIHHQzazBwPzD2TI0Hz8P4yJgFoVg4sM9
                  BYNSwTiKVjwzdwKCAQEA0OKPNOu4w9fzAmeluU0PGRG7HYouiqn267E4iFvil/to
                  MiPJ0ByyJ32XT/pVjU7pWvBoEAIceJkwFUFxXyHTEPLKc83q+WpOrHoNndJDKTzX
                  CVQcqsTTxeuUlaBz7qO8x0qLuPw1FiNCvSS/00Tr1BzroujIYX6oFqWZSyKTOkPV
                  9+gwgWEHc4Zm2EHCfAa5pRqMCcjDi/QAMsctavOruljsZPLEuVwYxSmIiuouTFGH
                  DIswf3ICPeLteXh2yhyEL2e6FkslyBZRFbBXfwgZC3REhYvMq/xq5r5lNqTFKEvf
                  j0uhpLxwd8tcZQdvn+TgzzKbl2HND9el6HhyXR+QHwKCAQEA2sk81QDtyigI8yrL
                  Xsehy9Q8GoJ2WQmdtgubAgUNKe5fneCtvrnk1yNra2ELQHrkcjW+Xx4tIYhAsjYi
                  VdXfxAp8jorCVnBm7uozFWAWubOGi/DEMxbd37RWpJVbYfdW2XbRbgoQmDFKurRh
                  dMw4N3xksPl6eYIc5ueRcGZ/o21ivt6vZvVMBFWqw3zpbgQPOZ04/9vtKewKF7od
                  7TiLgjOHu9Z9AjkeIJplYLg4ghD8RrKJVlavtqyeAbL/+LVxad8n2dK6dZe6zctY
                  BJwFgxiadao3NivOKGacrr3276qVgi3SeJs1bjaibGLJVLZqBt8tXhSuqoCX0iOz
                  t+mSEQKCAQBaNNz/T6TU/pc1PKl24m5Yty2FTj1XKJs3oar2SCgM1kdjD82BkELn
                  hvcnVMZJZgCkgxmNgDvnYNBA/agGG0dZFGCVriGBYIVlOrhSpZDXaCy9HJPcs295
                  E4lxLH+kWRWXQvwgANq0GrohkJM+m470ZSDlk32ljNruHMmchuvpx43Jp337AXoE
                  S9ByJ8PjZ8wYHuTG/OplsBO92gIlI+HPccN0vNpz6e/QhWUwCH3B+5tEsX9aKlQJ
                  gcxoHru+AJ6dEkBsjDteszSFF0hR1Z9rMOS+f2b+Bt3rk+GFvZZfFpUO/uxphe9T
                  7ICUKKft9xuWnxZOQ7AY3VoKkKliydSlAoIBAFttvCHc/utzR2YkWlaGRXbwv3bD
                  3QurKz5V8uws864MYk3Q2Ahmoww4Hc6fn10bHQH0mh4fJ0vETvQjzE5mh0uR4lQT
                  CVt73r1zRhNSpukgwnjHDdn7r/GtYU0RDHqZMUzYn/1cSGF9e3xt9uzM7YRNclV7
                  5YyL05FrYK8DcOz45VRNpWtOhtRs0hLs5guA23/G8UlW1qtMcdUdoBlFQ+mZLZCN
                  ms9xNv2c55ceYALLC/KzML09pA0RoReHBbDdq5CCSJIFd6mHOdlgxzDBzcaHgGED
                  LO6hTb6jpf63JjyxZc+4nYfFS2R153GORUY/N4j3haUayE8YGSKTPRtEmjM="
                  # Key RSA Privada hasheada del usuario dbadmin
   
    - name: Agregar clave para usuario dbadmin
      authorized_key:
        user: dbadmin # Usuario a agregar la clave publica
        state: present # Especificar que la clave exista
        # Key RSA publica a copiar al servidor para el usuario dbadmin
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDGMSSFZtCKIprPh/Q8Rj6C4T6S0cHWLNHrjKyy6pnDjTP8/AT2+fvkUOiZEqYmNXug+DKg/JBsXFOs+cbhz7/B3MMCoERKOAG1wNfTvawGbAdX8CMynS20O83y73IhR1O8VjSUGoJvhkN69taIP6sQDbEpqxw0VVC11FA6O9qxsZ19muYHR6C1WCHWXEz6FpGtX7XMXVlb1BH96SQ2yNtz+XQUGnwhkLmTlbGh7kx6vPC+Ri/Dl/Zauo2LUuM0bVA1MUAGCkj+muISNU99KS+HWBuyYgb41FyElZcrvcUUBmlcbAaCfA1b3yW45lePkzT4BqIHrhFNjn+sYGrTK7E71/ZzDV/1GCdZGR2F3qFMhszAHDClxmel+Umt0VXfQIo1y4u9IhpCKc1nVtIWFFQm0lrPiUrw88EHJh2euRpbipvks1/5hWi2RDsfD4kILHdTh7T0C7yFcJRvqWGmXuAc2XHOhbxe62wsttr1EHYwzWt9DQI7QUQtCzcKvZ3ujT/55w2nFC4qBcQ1PrlWOs+hx7RzJn2r+tKyOrhqgUgMye2P+hZhbEUTbTE+GFopRn2/cP26iL/sp7pHOASBjRTJo0jt/1JhA/jH9ITY2IUmL9o0bIlYWmQehbQwx+YuIlCSC/IRVqD2TuPBZuZSRYyaJxiBoGvR7BXFDqw8xKYraQ== root@bd.gsmf.local"
