---
    - name: Crear dbAdmin
      user: 
        name: dbadmin
        comment: DB Admin user
        group: wheel
        password: ""
                  # Key RSA Privada hasheada del usuario dbadmin
   
    - name: Agregar clave para usuario dbadmin
      authorized_key:
        user: dbadmin # Usuario a agregar la clave publica
        state: present # Especificar que la clave exista
        # Key RSA publica a copiar al servidor para el usuario dbadmin
        key: ""
