version: '2'
services: 
    aplicacion:
        image: php:7.2-apache
        container_name: ServerAppPhp
        ports:
            - "80:80"
        volumes: 
            - /opt/ServerAppPhp/html:/var/www/html
